import { Room } from "@/types/roomType";


export const rooms: {[key: number]: Room} = {
  94: {
    roomId: 94,
    description: "Labor",
    Level: 1,
    favorite: true,
  },
  189: {
    roomId: 189,
    description: "Cafe",
    Level: 2,
    favorite: true,
  },
  55: {
    roomId: 55,
    description: "Patient",
    Level: 3,
    favorite: true,
  },
  23: {
    roomId: 23,
    description: "Patient",
    Level: 0,
    favorite: true,
  },
  12: {
    roomId: 12,
    description: "Patient",
    Level: 1,
    favorite: true,
  },
  45: {
    roomId: 45,
    description: "Patient",
    Level: 2,
    favorite: true,
  },
  67: {
    roomId: 67,
    description: "Pause",
    Level: 3,
    favorite: true,
  },
  178: {
    roomId: 178,
    description: "Pause",
    Level: 0,
    favorite: true,
  },
  101: {
    roomId: 101,
    description: "Operationssaal",
    Level: 2,
    favorite: true,
  },
  202: {
    roomId: 202,
    description: "Intensivstation",
    Level: 3,
    favorite: true,
  },
  305: {
    roomId: 305,
    description: "Notaufnahme",
    Level: 0,
    favorite: true,
  },
  140: {
    roomId: 140,
    description: "Radiologie",
    Level: 1,
    favorite: true,
  },
  210: {
    roomId: 210,
    description: "Mitarbeiterzimmer",
    Level: 2,
    favorite: true,
  },
  315: {
    roomId: 315,
    description: "Labor",
    Level: 3,
    favorite: true,
  },
  123: {
    roomId: 123,
    description: "Apotheke",
    Level: 1,
    favorite: false,
  },
  56: {
    roomId: 56,
    description: "Chirurgie",
    Level: 4,
    favorite: false,
  },
  98: {
    roomId: 98,
    description: "Gipsraum",
    Level: 0,
    favorite: false,
  },
  47: {
    roomId: 47,
    description: "Kantine",
    Level: 1,
    favorite: false,
  },
  211: {
    roomId: 211,
    description: "Wartezimmer",
    Level: 2,
    favorite: false,
  },
  301: {
    roomId: 301,
    description: "MRT",
    Level: 3,
    favorite: false,
  },
  420: {
    roomId: 420,
    description: "Röntgen",
    Level: 4,
    favorite: false,
  },
  35: {
    roomId: 35,
    description: "Büro",
    Level: 0,
    favorite: false,
  },
  59: {
    roomId: 59,
    description: "Sprechzimmer",
    Level: 1,
    favorite: false,
  },
  110: {
    roomId: 110,
    description: "Physiotherapie",
    Level: 1,
    favorite: false,
  },
  225: {
    roomId: 225,
    description: "Ultraschall",
    Level: 2,
    favorite: false,
  },
  333: {
    roomId: 333,
    description: "Endoskopie",
    Level: 3,
    favorite: false,
  },
  421: {
    roomId: 420,
    description: "Gynäkologie",
    Level: 4,
    favorite: false,
  },
  58: {
    roomId: 58,
    description: "Kardiologie",
    Level: 0,
    favorite: false,
  },
  275: {
    roomId: 275,
    description: "HNO",
    Level: 2,
    favorite: false,
  },
  310: {
    roomId: 310,
    description: "Neurologie",
    Level: 3,
    favorite: false,
  },
  48: {
    roomId: 48,
    description: "Onkologie",
    Level: 0,
    favorite: false,
  },
  95: {
    roomId: 95,
    description: "Urologie",
    Level: 1,
    favorite: false,
  },
  365: {
    roomId: 365,
    description: "Dermatologie",
    Level: 3,
    favorite: false,
  },
  500: {
    roomId: 500,
    description: "Kinderstation",
    Level: 1,
    favorite: true,
  },
  501: {
    roomId: 501,
    description: "Augenheilkunde",
    Level: 2,
    favorite: true,
  },
  502: {
    roomId: 502,
    description: "HNO",
    Level: 3,
    favorite: true,
  },
  503: {
    roomId: 503,
    description: "Zahnarzt",
    Level: 0,
    favorite: true,
  },
  504: {
    roomId: 504,
    description: "Kardiologie",
    Level: 1,
    favorite: true,
  },
  505: {
    roomId: 505,
    description: "Orthopädie",
    Level: 2,
    favorite: true,
  },
  506: {
    roomId: 506,
    description: "Pädiatrie",
    Level: 3,
    favorite: true,
  },
  507: {
    roomId: 507,
    description: "Dermatologie",
    Level: 0,
    favorite: true,
  },
  508: {
    roomId: 508,
    description: "Psychiatrie",
    Level: 1,
    favorite: true,
  },
  509: {
    roomId: 509,
    description: "Gastroenterologie",
    Level: 2,
    favorite: true,
  },
  510: {
    roomId: 510,
    description: "Nephrologie",
    Level: 3,
    favorite: true,
  },

  // Dieser Raum crashed den Roboter
  666: {
    roomId: 666,
    description: "FinalDestination",
    Level: 3,
    favorite: false,
  },
};